### ISSUE TITLE
step 5 updating kabanero CR is not updating correctly 

### ISSUE THREAD

**Issue by oiricaud** [ibm-cloud-architecture/devops-demo-kabanero-pipelines#10]
Given:

``` yaml

 stacks:
      pipelines:
      - https:
          url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.1/default-kabanero-pipelines.tar.gz
        id: default
        sha256: 64aee2805d36127c2f1e0e5f0fc6fdae5cef19360c1bb506137584f3bd0988cc
      - https:
          url: https://github.com/oiricaud/pipelines/releases/download/v60.0/default-kabanero-pipelines.tar.gz
        id: package-release-update-pl
        sha256: 86b1902f9f7ce0911f759bbe9e11c27075a3b1f7cca40de59df19eab9afca45d
      repositories:
      - https:
          url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.3/kabanero-stack-hub-index.yaml

```

the `run.sh` file is not updating a pipeline instance correctly.
